lrdp-v2: fix printout memory attributes
Fix UnboundLocalError for local variable
'attr_indx_str' referenced before assignment

----------begin IOMMU----------
!!! Exception while running IOMMU
Traceback (most recent call last):
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\ramparse.py", line 376, in <module>
    p.cls(dump).parse()
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\parsers\iommu.py", line 352, in parse
    parse_aarch64_tables(self.ramdump, d, domain_num)
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\aarch64iommulib.py", line 444, in parse_aarch64_tables
    flat_mapping = create_flat_mappings(ramdump, d.pg_table, d.level)
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\aarch64iommulib.py", line 403, in create_flat_mappings
    tmp_mapping)
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\aarch64iommulib.py", line 336, in parse_2nd_level_table
    page_size, attr_indx, shareability, xn_bit, True)
  File "linux-ramdump-parser-v2\linux-ramdump-parser-v2\aarch64iommulib.py", line 185, in add_flat_mapping
    map = FlatMapping(virt, phy_addr, map_type_str, page_size, attr_indx_str,
UnboundLocalError: local variable 'attr_indx_str' referenced before assignment
------------end IOMMU----------

Change-Id: I604c920ef302ee9f53d31aa7a0c6edf20c25e7c9
Fixes: If05b35e7855 ("lrdp-v2: Change to printout memory attributes")